### Numpy Library
    - Processing for  N-Dimensional array

In [9]:
import numpy as np
li=[1,2,3,4.5,'c,']
a=np.array(li)
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
rn=np.random.randint(0,100,size=5)
rn
rn=np.random.randint(0,2,size=(3,3))
rn
rn=np.random.randint(0,2,size=(3,3,3,3))
rn.shape
rn.size
rn.shape
rn.nbytes
rn.itemsize


4

In [48]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [55]:
gr=np.arange(1,13).reshape(3,3)
gr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,3])
print(x1, x2, x3)

[1 2 3] [] [99 99  3  2  1]


### Pandas
 **Use Cases**
   - Data Cleaning
   - Data Transformation
   - Data Analysis
 
**Notations**
 - Series
 - DataFrame

In [79]:
import pandas as pd
internal1={'s1':21,'s2':18,'s3':24}
internal1=pd.Series(internal1)
internal1
internal2={'s1':23,'s2':17,'s3':15,}
internal2=pd.Series(internal2)
internal2

s1    23
s2    17
s3    15
dtype: int64

In [90]:
final={'Internal1':internal1,'internal2':internal2}
final=pd.DataFrame(final)
final

Internal1  internal2
s1         21         23
s2         18         17
s3         24         15

In [88]:
final.columns # Names of All Columns
final.values # List of all rows

array([[21, 23],
       [18, 17],
       [24, 15]], dtype=int64)

In [94]:
final.values[2,0]
final.values[2][0]
for row in final.values:
    print('Internal1 - '+str(row[0])+','+'Internal2 - '+str(row[1]))

Internal1 - 21,Internal2 - 23
Internal1 - 18,Internal2 - 17
Internal1 - 24,Internal2 - 15


In [103]:
final.loc[4] = [24,20]

In [107]:
final=final.drop(4)
final

Internal1  internal2
s1         21         23
s2         18         17
s3         24         15
s4         24         20

In [108]:
final.values[2,0]=25

In [109]:
final

Internal1  internal2
s1         21         23
s2         18         17
s3         25         15
s4         24         20

In [110]:
final.values[2]=[23,24]

In [113]:
final

Internal1  internal2
s1         21         23
s2         18         17
s3         23         24
s4         24         20

In [114]:
import pandas as pd
# Reading CSV File Data
incomedf=pd.read_csv('DataFiles/income.csv')
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [123]:
# Extract income of all states in 2013
for i in incomedf.values:
    print(i[1],':',i[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [126]:
# Average income of particular state(Arizona)
sum=0
for i in range(2,11):
    sum+=incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [133]:
# Average of income of all states
sum=0
c=0
for row in incomedf.values:
    sum+=row[-2]
    c+=1
sum/len(incomedf.values[-2][:-2])
    

27799.333333333332